name: Update Proton VPN IPs
on:
  push:
    branches: [ "main" ]
    paths: 
      - 'inputs/proton_vpn_logicals.json'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'inputs/proton_vpn_logicals.json'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Update server ips from logicals file
        run: |
          cat inputs/proton_vpn_logicals.json| jq  --raw-output '.LogicalServers[].Servers[].EntryIP' | sort | uniq > protonvpn-ips.txt

      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Automatically updated IP lists from logicals."
